# Generated by Django 3.1.1 on 2020-09-17 09:25

from django.db import migrations, models
from django.utils.timezone import utc
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 10, 15, 9, 779689,tzinfo=utc) ,verbose_name='date closed'),
            preserve_default=False,
        ),
    ]
